### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by woodsbr6** [woodsbr6/MI-449-SS17-740-html-semantic-elements-5BSgA-#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://woodsbr6.github.io/MI-449-SS17-740-html-semantic-elements-5BSgA-/) and meets the following criteria:

- [x] Place a `nav` element at the top of the page that includes (fake) links to other pages
- [x] Use the `main` element appropriately
- [x] Include three products your store sells, all listed on the same Products page
- [x] For each product, correctly use an `article`, `header`, and `footer` element
- [x] Use `figure` and `figcaption` to show what each product looks like
- [x] Each product includes a `nav` element with one or more links to related products (the links don't have to go anywhere)
- [x] Use an `aside` in one or more products to advertise a promotion or discount for that product

**Comment by KatieMFritz** [comment]
Hi Brielle, good start to this! 🎨 😄 

There are quite a few [HTML errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwoodsbr6.github.io%2FMI-449-SS17-740-html-semantic-elements-5BSgA-%2F). See if you can get all those cleaned up and then resubmit. 

Some tips to make this easier/faster:
- Start with the errors that `linter-htmlhint` is giving you in Atom (if you don't have that linter installed, you can find instructions [in this lesson](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-boilerplate-linting-and-code-style/2)), rather than going off the W3 validator's messages. 
- Then copy and paste your updated HTML into the ["direct input" tab on the W3 validator](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-boilerplate-linting-and-code-style/2) so you don't have to keep updating `gh-pages`.
- Once there are no more errors, then push to both your `master` branch and `gh-pages`, then check the `gh-pages` link again in the validator.

If you have questions about any of the errors or warnings, feel free to Slack me! Otherwise, let me know once you've updated and checked everything again. 😸

**Comment by woodsbr6** [comment]
fixed!

**Comment by KatieMFritz** [comment]
Hi Brielle! I'm still seeing errors in the [HTML Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwoodsbr6.github.io%2FMI-449-SS17-740-html-semantic-elements-5BSgA-%2F). Are you?

**Comment by woodsbr6** [comment]
Ok i fixed the Errors, does the Warnings have to be addressed as well?

**Comment by KatieMFritz** [comment]
Good job fixing the errors! 🎉 Responding to the warnings would be useful, but it's not totally necessary. 🙂 

This looks really solid now. 💥 The only thing I would change is getting rid of the `section` that wraps the Art Sale `article`s. It's not _wrong_, but it's not necessary. 

However, since it's not wrong, you can skip it! :shipit:
